### ISSUE TITLE
Consider changing special schedule API to be more RESTful/CRUDful

### ISSUE THREAD

**Issue by shickey** [Foo-Bear/beartime-server#10]
We should consider changing some of the API endpoints to be more RESTful. In particular, using `POST /modifyschedule` to perform a deletion probably doesn't make sense. Instead, we should think about adopting a more CRUDful approach. Maybe something like:

`GET /day/:day` retrieves a day
`POST /day/:day` creates a special schedule
`PUT/PATCH /day/:day` modifies a special schedule
`DELETE /day/:day` deletes a special schedule (i.e., reverts it to the standard daily schedule)

**Comment by kschamplin19** [comment]
I had not thought of that! Brilliant! I'll start working on it right away.

**Comment by kschamplin19** [comment]
Closing as this is solved.
